//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack product.
//
// Copyright (c) 2008 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License.
// You can find a copy of the Commercial License in the Particle Universe package.
//-----------------------------------------------------------------------------------------------------------------------
system PUMediaPack/BlackHole
{
    technique
    {
        renderer Billboard                           {}
        material                                     PUMediaPack/Flare_04
        default_particle_width                       300
        default_particle_height                      300
        visual_particle_quota                        2500
        emitter                                      SphereSurface
        {
            sphere_surface_em_radius                 400
            emission_rate                            200
            velocity                                 100
            time_to_live                             3
            direction                                0 1 0
        }
        affector                                     Colour
        {
            colour_aff_time_colour                   0.0 0.0 0.0 0.2
            colour_aff_time_colour                   0.9 0.8 0.8 1.0
            colour_aff_time_colour                   1.0 1.0 1.0 1.0
        }
        
        affector                                     Gravity
        {
            gravity                                  900000
        }

        affector                                     Scale
        {
            xyz_scale                                -150
        }
    }

    technique
    {
        material                                    PUMediaPack/Streak_03
        visual_particle_quota                       250
        renderer Billboard
        {
            billboard_type                          oriented_self
        }

        emitter                                     Point
        {
            particle_width                          dyn_random
            {
                min                                 40
                max                                 80
            }
            particle_height                         dyn_random
            {
                min                                 1500
                max                                 2000
            }
            emission_rate                           30
            angle                                   360
            velocity                                1
            time_to_live                            4
            direction                               0 1 0
            colour                                  0.1 0.1 1.0
        }

        affector                                    Scale
        {
            x_scale                                 -40
        }

        affector                                    Scale
        {
            y_scale                                 -1500
        }

        use_alias                                   $PUMediaPack/ColourAffectorFade_06
    }
}


//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
system PUMediaPack/ColouredStreaks
{
    technique
    {
        position                                    600 -200 0
        default_particle_width                      70
        default_particle_height                     800
        visual_particle_quota                       3000
        emitted_emitter_quota                       30
        renderer Billboard
        {
            billboard_origin                        center
        }
        material                                    PUMediaPack/Streak_04

        emitter                                     Point
        {
            emits                                   emitter_particle    flares
            angle                                   0
            emission_rate                           4
            direction                               1 0 0
            velocity                                dyn_random
            {
                min                                 0
                max                                 200
            }
            time_to_live                            dyn_random
            {
                min                                 4
                max                                 6
            }
            colour                                  1 0 0
        }

        emitter                                     Point    flares
        {
            angle                                   0
            emission_rate                           100
            time_to_live                            2
            direction                               0 1 0
        }

        affector                                    Colour
        {
            colour_aff_time_colour                  0 1 0 0
            colour_aff_time_colour                  0.2 0.3 0.1 0.6
            colour_aff_time_colour                  0.4 1 1 0
            colour_aff_time_colour                  0.8 0.3 1 0
            colour_aff_time_colour                  1 0 0 0
        }

        affector                                    PathFollower
        {
            exclude_emitter                         "flares"
            path_follower_point                     -100 -10 -40
            path_follower_point                     100 -50 40
            path_follower_point                     0 -200 -10
            path_follower_point                     100 100 70
            path_follower_point                     400 260 60
        }
    }
}


//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
system PUMediaPack/Woosh
{
    technique
    {
        position                                    0 -100 0
        visual_particle_quota                       1
        default_particle_width                      10
        default_particle_height                     10
        material                                    PUMediaPack/Ring_14
        renderer Billboard                          
        {
            billboard_type                          perpendicular_common
            common_direction                        0 1 0
            common_up_vector                        0 0 1
        }
        
        emitter                                     Point    wooshEmitter
        {
            emission_rate                           1
            force_emission                          true
            time_to_live                            1
            direction                               0 0 0
        }
        
        affector                                    Scale
        {
            xyz_scale                               1000
        }
        
        use_alias                                   $PUMediaPack/ColourAffectorFade_01

        use_alias                                   $PUMediaPack/OnClearDoStopSystem
    }
}


//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
system PUMediaPack/DirtExplosion
{
	scale 											0.1 0.1 0.1
    technique
    {
        visual_particle_quota                       30
        material                                    PUMediaPack/Dirt_11
        renderer                                    Billboard
        {
            billboard_type                          oriented_self
            billboard_origin                        bottom_center
        }
        
        emitter                                     Point
        {
            particle_width                          dyn_random
            {
                min                                 5
                max                                 12.5
            }
            particle_height                         dyn_random
            {
                min                                 20
                max                                 60
            }
            emission_rate                           15
            angle                                   40
            force_emission                          true
            time_to_live                            dyn_random
            {
                min                                 1.8
                max                                 3.4
            }
            direction                               0 1 0
            velocity                                1
            colour                                  0.76 0.7 0.64 1.0
        }
        
        emitter                                     Point
        {
            particle_width                          dyn_random
            {
                min                                 2.5
                max                                 7.5
            }
            particle_height                         dyn_random
            {
                min                                 2
                max                                 7.5
            }
            emission_rate                           15
            angle                                   40
            force_emission                          true
            time_to_live                            dyn_random
            {
                min                                 1.8
                max                                 3.4
            }
            direction                               0 0.5 0
            velocity                                1
            colour                                  0.76 0.7 0.64 1.0
        }

        affector                                    Scale
        {
            x_scale                                 dyn_curved_linear
            {
                control_point                       0.0 1000
                control_point                       0.2 100
                control_point                       0.3 30
                control_point                       1.0 0.0
            }

            y_scale                                 dyn_curved_linear
            {
                control_point                       0.0 1000
                control_point                       0.1 400
                control_point                       0.2 100
                control_point                       1.0 20.0
            }

        }

        use_alias                                   $PUMediaPack/ColourAffectorFade_07
    }

    technique
    {
        visual_particle_quota                       100
        material                                    PUMediaPack/Smoke_11
        renderer                                    Billboard
        {
            billboard_type                          oriented_self
        }
        
        emitter                                     Point
        {
            all_particle_dimensions                 dyn_random
            {
                min                                 5
                max                                 20
            }
            emission_rate                           100
            angle                                   10
            force_emission                          true
            time_to_live                            4
            direction                               0 1 0
            velocity                                dyn_random
            {
                min                                 300
                max                                 700
            }
            colour                                  0.32 0.3 0.2 1.0
        }

        affector                                    LinearForce
        {
            force_aff_vector                        0 -500 0
        }

        use_alias                                   $PUMediaPack/ColourAffectorFade_07
    }
}



//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
system PUMediaPack/ElectroShield
{
    fast_forward                                    1 0.1
    technique
    {
        renderer                                    Billboard
        {
            billboard_type                          oriented_shape
            billboard_origin                        bottom_center
        }
        material                                    PUMediaPack/Spark_01
        default_particle_width                      80
        default_particle_height                     1
        visual_particle_quota                       100
        emitted_emitter_quota                       10

        emitter                                     Point    ElectroPoint
        {
            emission_rate                           4
            time_to_live                            2
            emits                                   emitter_particle   ElectroCircle
            duration                                5
            direction                               0 0 0
        }

        emitter                                     Circle    ElectroCircle
        {
            circle_em_radius                        200
            circle_em_random                        false
            circle_em_step                          0.4
            emission_rate                           16
            direction                               0 1 0
            velocity                                40
            time_to_live                            1
            force_emission                          true
        }

        affector                                    Align
        {
            exclude_emitter                         "ElectroPoint"
            align_aff_resize                        true

        }

        affector                                    Randomiser
        {
            exclude_emitter                         "ElectroPoint"
            rand_aff_direction                      false
            rand_aff_max_deviation_x                2
            rand_aff_max_deviation_y                4
            rand_aff_max_deviation_z                2
            rand_aff_time_step                      0.01
        }

        use_alias                                   $PUMediaPack/ColourAffectorFade_04

        use_alias                                   $PUMediaPack/OnClearDoStopSystem
    }
}





//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/BoxEmitter
{
    emitter                                     Box
    {
        emission_rate                           200
        angle                                   10
        direction                               0 1 0
        box_em_width                            100
        box_em_height                           4
        box_em_depth                            100
        velocity                                dyn_random
        {
            min                                 100
            max                                 200
        }
        time_to_live                            dyn_random
        {
            min                                 1
            max                                 3
        }
        particle_width                          dyn_random
        {
            min                                 30
            max                                 70
        }
        particle_height                         dyn_random
        {
            min                                 13
            max                                 40
        }
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/GravityAffectorLarge
{
    affector                                    Gravity
    {
        position                                0 130 0
        gravity                                 3000
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/GravityAffectorSmall
{
    affector                                    Gravity
    {
        position                                0 130 0
        gravity                                 2500
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/ScaleAffectorLarge
{
    affector                                    Scale
    {
        x_scale                                 -5
        y_scale                                 dyn_random
        {
            min                                 4
            max                                 75
        }
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/ScaleAffectorSmall
{
    affector                                    Scale
    {
        x_scale                                 -5
        y_scale                                 dyn_random
        {
            min                                 3
            max                                 26
        }
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/ParticleFollower
{
    affector                                    ParticleFollower
    {
        follower_min_distance                   4
        follower_max_distance                   35
    }
}
//-----------------------------------------------------------------------------
alias                                           $PUMediaPack/Fire/ColourAffector
{
    affector                                    Colour
    {
        colour_aff_time_colour                  0 0 0 0
        colour_aff_time_colour                  0.1 1 1 1
        colour_aff_time_colour                  1 0 0 0
    }
}
//-----------------------------------------------------------------------------
system PUMediaPack/Fireplace_01
{
    technique
    {
        material                                PUMediaPack/Fire_01
        visual_particle_quota                   450

        // Renderer
        renderer Billboard         
        {
        }

        // Emitter
        use_alias                               $PUMediaPack/Fire/BoxEmitter

        // Affectors
        use_alias                               $PUMediaPack/Fire/GravityAffectorLarge
        use_alias                               $PUMediaPack/Fire/ScaleAffectorLarge
        use_alias                               $PUMediaPack/Fire/ColourAffector
    }

    technique
    {
        material                                PUMediaPack/Fire_02
        visual_particle_quota                   450

        // Renderer
        renderer Billboard         
        {
            billboard_type                      oriented_self
        }

        // Emitter
        use_alias                               $PUMediaPack/Fire/BoxEmitter

        // Affectors
        use_alias                               $PUMediaPack/Fire/GravityAffectorSmall
        use_alias                               $PUMediaPack/Fire/ScaleAffectorSmall
        use_alias                               $PUMediaPack/Fire/ParticleFollower
        use_alias                               $PUMediaPack/Fire/ColourAffector
    }
}

//-----------------------------------------------------------------------------
system PUMediaPack/Fireplace_02
{
    technique
    {
        material                                PUMediaPack/Fire_03
        visual_particle_quota                   450

        // Renderer
        renderer Billboard         
        {
        }

        // Emitter
        use_alias                               $PUMediaPack/Fire/BoxEmitter

        // Affectors
        use_alias                               $PUMediaPack/Fire/GravityAffectorLarge
        use_alias                               $PUMediaPack/Fire/ScaleAffectorLarge
        use_alias                               $PUMediaPack/Fire/ColourAffector
    }

    technique
    {
        material                                PUMediaPack/Fire_04
        visual_particle_quota                   450

        // Renderer
        renderer Billboard         
        {
            billboard_type                      oriented_self
        }

        // Emitter
        use_alias                               $PUMediaPack/Fire/BoxEmitter

        // Affectors
        use_alias                               $PUMediaPack/Fire/GravityAffectorSmall
        use_alias                               $PUMediaPack/Fire/ScaleAffectorSmall
        use_alias                               $PUMediaPack/Fire/ParticleFollower
        use_alias                               $PUMediaPack/Fire/ColourAffector
    }
}
