#ifndef LEVEL_EVENTS_H
#define LEVEL_EVENTS_H
namespace OUAN
{
	//LEVEL 2 CUTSCENES
	const std::string CUTSCENE_1_LEVEL_START="LEVEL_START";
	const std::string CUTSCENE_2_FIRST_CHANGE_WORLD="FIRST_CHANGE_WORLD";

	//LEVEL 2 EVENTS
	const std::string EVENT_FIRST_CHANGE_WORLD_ACTIVATED="FIRST_CHANGE_WORLD_ACTIVATED";


	//...
}

#endif