#ifndef LEVEL_EVENTS_H
#define LEVEL_EVENTS_H
namespace OUAN
{
	//CLOCK CUTSCENES
	const std::string CUTSCENE_1_CLOCK_INTRO="CLOCK_INTRO";
	const std::string CUTSCENE_2_LEVEL_ENTRANCE="LEVEL_ENTRANCE_2";

	//LEVEL 2 CUTSCENES
	const std::string CUTSCENE_1_LEVEL_START="LEVEL_START";
	const std::string CUTSCENE_1_1_PLATFORM_TO_MOUNTAIN_1="PLATFORM_TO_MOUNTAIN_1";
	const std::string CUTSCENE_2_FIRST_CHANGE_WORLD="FIRST_CHANGE_WORLD";
	const std::string CUTSCENE_3_BOMBS_PUZZLE_START="BOMBS_PUZZLE_START";
	const std::string CUTSCENE_3_1_BOMBS_PUZZLE_PLACE_BOMB="BOMBS_PUZZLE_PLACE_BOMB";
	const std::string CUTSCENE_4_BOMBS_PUZZLE_END="BOMBS_PUZZLE_END";
	const std::string CUTSCENE_5_NIGHT_GOBLIN_APPEARS="NIGHT_GOBLIN_APPEARS";
	const std::string CUTSCENE_6_NIGHT_GOBLIN_APPEARS="NIGHT_GOBLIN_APPEARS";
	const std::string CUTSCENE_7_1_BOSSS_PLATFORM="1_BOSSS_PLATFORM";
	const std::string CUTSCENE_7_2_BOSSS_PLATFORM="2_BOSSS_PLATFORM";
	const std::string CUTSCENE_7_3_BOSSS_PLATFORM="3_BOSSS_PLATFORM";
	const std::string CUTSCENE_8_BOSS_STATUES="BOSS_STATUES";
	const std::string CUTSCENE_8_0_BOSS_STATUES_END="BOSS_STATUES_END";
	const std::string CUTSCENE_8_1_PLATFORMS_TO_FINAL_BOSS="PLATFORMS_TO_FINAL_BOSS";
	const std::string CUTSCENE_9_FINAL_BOSS_START="FINAL_BOSS_START";
	const std::string CUTSCENE_10_1_FINAL_BOSS_HIT_1="FINAL_BOSS_HIT_1";
	const std::string CUTSCENE_10_2_FINAL_BOSS_HIT_2="FINAL_BOSS_HIT_2";
	const std::string CUTSCENE_10_3_FINAL_BOSS_HIT_3="FINAL_BOSS_HIT_3";

	//LEVEL 2 EVENTS
	const std::string FIRST_CHANGE_WORLD_GAME_OBJECT="changeworld#island1_tower1";
	const std::string BOSS_STATUES_CHANGE_WORLD_GAME_OBJECT="changeworld#BOSS_STATUES";
	const std::string EVENT_FIRST_CHANGE_WORLD_ACTIVATED="FIRST_CHANGE_WORLD_ACTIVATED";
	const std::string BOMB_EXPLODED_NEAR_BRIGDGE_ROCK="BOMB_EXPLODED_NEAR_BRIGDGE_ROCK";
	const std::string NIGHT_GOBLIN_DEFEATED="NIGHT_GOBLIN_DEFEATED";
	const std::string BOSS_1_SWITCH_ACTIVATED="BOSS_1_SWITCH_ACTIVATED";
	const std::string BOSS_2_SWITCH_ACTIVATED="BOSS_2_SWITCH_ACTIVATED";
	const std::string BOSS_3_SWITCH_ACTIVATED="BOSS_3_SWITCH_ACTIVATED";
	const std::string BOSS_1_STATUE_DEFEATED="BOSS_1_STATUE_DEFEATED";
	const std::string BOSS_2_STATUE_DEFEATED="BOSS_2_STATUE_DEFEATED";
	const std::string BOSS_3_STATUE_DEFEATED="BOSS_3_STATUE_DEFEATED";
	const std::string BOSS_4_STATUE_DEFEATED="BOSS_4_STATUE_DEFEATED";
	const std::string BOSS_PLATFORM_PUZZLE_END="BOSS_PLATFORM_PUZZLE_END";
	const std::string BOSS_HIT_1_DONE="BOSS_HIT_1_DONE";
	const std::string BOSS_HIT_2_DONE="BOSS_HIT_2_DONE";
	const std::string BOSS_HIT_3_DONE="BOSS_HIT_3_DONE";
	//...
}

#endif