#ifndef LEVEL_EVENTS_H
#define LEVEL_EVENTS_H
namespace OUAN
{

	//CLOCK CUTSCENES

	const std::string CUTSCENE_1_CLOCK_INTRO="CLOCK_INTRO";
	const std::string CUTSCENE_2_LEVEL_ENTRANCE="LEVEL_ENTRANCE_2";

	//LEVEL 2 CUTSCENES

	const std::string CUTSCENE_1_LEVEL_START="LEVEL_START";
	const std::string CUTSCENE_1_1_PLATFORM_TO_MOUNTAIN_1="PLATFORM_TO_MOUNTAIN_1";
	const std::string CUTSCENE_2_FIRST_CHANGE_WORLD="FIRST_CHANGE_WORLD";
	const std::string CUTSCENE_3_BOMBS_PUZZLE_START="BOMBS_PUZZLE_START";
	const std::string CUTSCENE_4_BOMBS_PUZZLE_END="BOMBS_PUZZLE_END";
	const std::string CUTSCENE_5_NIGHT_GOBLIN_APPEARS="NIGHT_GOBLIN_APPEARS";
	const std::string CUTSCENE_6_NIGHT_GOBLIN_APPEARS="NIGHT_GOBLIN_APPEARS";
	const std::string CUTSCENE_7_1_TRIPOLLOS_PLATFORM="1_TRIPOLLOS_PLATFORM";
	const std::string CUTSCENE_7_2_TRIPOLLOS_PLATFORM="2_TRIPOLLOS_PLATFORM";
	const std::string CUTSCENE_7_3_TRIPOLLOS_PLATFORM="3_TRIPOLLOS_PLATFORM";
	const std::string CUTSCENE_8_TRIPOLLO_STATUES="TRIPOLLO_STATUES";
	const std::string CUTSCENE_8_1_PLATFORMS_TO_FINAL_BOSS="PLATFORMS_TO_FINAL_BOSS";
	const std::string CUTSCENE_9_FINAL_BOSS_START="FINAL_BOSS_START";
	const std::string CUTSCENE_10_FINAL_BOSS_END="FINAL_BOSS_END";


	//LEVEL 2 EVENTS
	const std::string FIRST_CHANGE_WORLD_GAME_OBJECT="changeworld#island1_tower1";
	const std::string EVENT_FIRST_CHANGE_WORLD_ACTIVATED="FIRST_CHANGE_WORLD_ACTIVATED";
	const std::string BOMB_EXPLODED_NEAR_BRIGDGE_ROCK="BOMB_EXPLODED_NEAR_BRIGDGE_ROCK";
	const std::string NIGHT_GOBLIN_DEFEATED="NIGHT_GOBLIN_DEFEATED";
	const std::string TRIPOLLO_1_SWITCH_ACTIVATED="TRIPOLLO_1_SWITCH_ACTIVATED";
	const std::string TRIPOLLO_2_SWITCH_ACTIVATED="TRIPOLLO_2_SWITCH_ACTIVATED";
	const std::string TRIPOLLO_3_SWITCH_ACTIVATED="TRIPOLLO_3_SWITCH_ACTIVATED";
	const std::string TRIPOLLO_PLATFORM_PUZZLE_END="TRIPOLLO_PLATFORM_PUZZLE_END";
	const std::string FINAL_BOSS_DEFEATED="FINAL_BOSS_DEFEATED";
	//...
}

#endif