system PU/any_jump_n
{
    scale                                       0.08 0.08 0.08
    technique Technique43
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   10
        material                                PU/any_jump_n
        spatial_hashtable_size                  2
        renderer                                Billboard
        {
            render_queue_group                  100
            common_direction                    1 1 1
        }
        emitter                                 Circle Emitter3
        {
            emission_rate                       dyn_random
            {
                min                             10
                max                             15
            }
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            mass                                2
            velocity                            20
            duration                            dyn_random
            {
                min                             0.6
                max                             0.8
            }
            circle_em_radius                    75
        }
        affector                                Randomiser Affector119
        {
        }
    }
}
