system PU/bag_hearts_fountain_double
{
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique 
    {
        visual_particle_quota                   30
        material                                PU/bag_hearts_fountain
        default_particle_width                  36
        default_particle_height                 36
        default_particle_depth                  36
        renderer                                Billboard
        {
        }
        emitter                                 Point myPointEmitter
        {
            angle                               30
            time_to_live                        2.5
            velocity                            250
            duration                            1
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -300 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
