system PU/changeworld_idle
{
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique 
    {
        position                                0 300 0
        visual_particle_quota                   200
        emitted_emitter_quota                   10
        material                                PU/changeworld_idle_2
        renderer                                Billboard
        {
        }
        emitter                                 Circle CircleEmitter
        {
            emission_rate                       20
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1.2
            }
            velocity                            10
            particle_width                      36
            particle_height                     36
            particle_depth                      36
            keep_local                          true
            direction                           0 0 0
            circle_em_radius                    300
        }
        affector                                Vortex 
        {
            vortex_aff_vector                   0 1 0
            vortex_aff_speed                    0.8
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
    technique 
    {
        visual_particle_quota                   250
        material                                PU/changeworld_idle
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             200
                max                             500
            }
            particle_width                      dyn_random
            {
                min                             20
                max                             90
            }
            particle_height                     dyn_random
            {
                min                             400
                max                             800
            }
            colour                              0.15 0.85 0.15 1
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
