system PU/ony_run_sand
{
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique Technique3
    {
        visual_particle_quota                   50
        material                                PU/ony_run_sand
        default_particle_width                  20
        default_particle_height                 20
        default_particle_depth                  20
        renderer                                Billboard
        {
        }
        emitter                                 Circle Emitter4
        {
            emission_rate                       12
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             150
                max                             250
            }
            duration                            0.8
            circle_em_radius                    50
        }
        affector                                Colour Affector8
        {
            colour_aff_time_colour              0    0.3 0.05 0.15 1
        }
    }
    technique 
    {
        material                                PU/ony_run_sand_3
        default_particle_width                  70
        default_particle_height                 70
        default_particle_depth                  70
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_random
            {
                min                             2
                max                             4
            }
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             400
                max                             500
            }
            duration                            1
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -800 0
        }
        affector                                Colour Affector9
        {
            colour_aff_time_colour              0    0.1 0.5 0.1 1
            colour_aff_time_colour              3    0.2 0.6 0.2 1
        }
    }
    technique 
    {
        material                                PU/ony_run_sand_4
        default_particle_width                  70
        default_particle_height                 70
        default_particle_depth                  70
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_random
            {
                min                             2
                max                             4
            }
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             400
                max                             500
            }
            duration                            1
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -800 0
        }
        affector                                Colour Affector9
        {
            colour_aff_time_colour              0    0.1 0.5 0.1 1
            colour_aff_time_colour              3    0.2 0.6 0.2 1
        }
    }
}
