system PU/ony_run_sand
{
    scale 0.05 0.05 0.05
    scale_velocity 0.05
    technique Technique3
    {
        visual_particle_quota                   10
        material                                PU/ony_run_sand
        renderer                                Billboard
        {
        }
        emitter                                 Circle Emitter4
        {
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            0.8
            circle_em_radius                    50
        }
        affector                                Colour Affector8
        {
            colour_aff_time_colour              0    0.8 0.3 0.15 1
            colour_aff_time_colour              3    1 1 1 1
        }
    }
    technique 
    {
        material                                PU/ony_run_sand_2
        default_particle_width                  70
        default_particle_height                 70
        default_particle_depth                  70
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       5
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             400
                max                             500
            }
            duration                            1
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -600 0
        }
        affector                                Colour Affector9
        {
            colour_aff_time_colour              0    0.1 0.9 0.1 1
            colour_aff_time_colour              3    0.2 1 0.2 1
        }
    }
}
