system PU/terrain_convex_changeworld
{
    technique main_technique
    {
        visual_particle_quota                   40
        material                                PU/terrain_convex_changeworld
        renderer                                Billboard
        {
        }
        emitter                                 Box main_emitter
        {
            emission_rate                       dyn_oscillate
            {
                oscillate_frequency             0.1
                oscillate_phase                 180
                oscillate_base                  500
                oscillate_amplitude             500
                oscillate_type                  sine
            }
            time_to_live                        0.15
            all_particle_dimensions             dyn_random
            {
                min                             12
                max                             72
            }
            direction                           0 0 0
            colour                              0.85 0.85 0.15 1
            box_em_width                        300
            box_em_height                       600
            box_em_depth                        300
        }
    }
}
