system PU/tripollo_surprise
{
    scale                                       0.05 0.05 0.05
    technique Technique3
    {
        visual_particle_quota                   1
        material                                PU/tripollo_surprise
        default_particle_width                  40
        default_particle_height                 40
        default_particle_depth                  40
        renderer                                Billboard
        {
        }
        emitter                                 Point Emitter4
        {
            time_to_live                        2.5
            velocity                            dyn_random
            {
                min                             10
                max                             12
            }
            duration                            2.5
        }
        affector                                Scale Affector10
        {
            xyz_scale                           100
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
