system PU/waterfall
{
    scale_velocity                              0.25
    scale                                       0.25 0.25 0.25
    technique 
    {
        visual_particle_quota                   100
        material                                PU/waterfall_1
        default_particle_width                  36
        default_particle_height                 36
        default_particle_depth                  36
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       6
            angle                               30
            time_to_live                        dyn_random
            {
                min                             2
                max                             2.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            all_particle_dimensions             dyn_random
            {
                min                             120
                max                             200
            }
            colour                              0.5 0.7 0.9 1
            box_em_width                        90
            box_em_height                       30
            box_em_depth                        90
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -80 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.2  1 1 1 1
            colour_aff_time_colour              0.4  1 1 1 1
            colour_aff_time_colour              1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique 
    {
        material                                PU/waterfall_2
        default_particle_width                  36
        default_particle_height                 36
        default_particle_depth                  36
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       12
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             180
                max                             240
            }
            box_em_width                        180
            box_em_height                       60
            box_em_depth                        180
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -400 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.2  1 1 1 1
            colour_aff_time_colour              0.4  1 1 1 1
            colour_aff_time_colour              1    1 1 1 0
            colour_operation                    multiply
        }
    }
}
