system PU/wave
{
    scale                                       0.5 0.5 0.5
    technique Technique19
    {
        visual_particle_quota                   100
        material                                PU/wave
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface Emitter23
        {
            emission_rate                       dyn_random
            {
                min                             3
                max                             4
            }
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             25
                max                             30
            }
            duration                            0.8
            position                            0 1 0
            colour                              0.65 0.65 0.45 1
            sphere_surface_em_radius            0.1
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
        affector                                LinearForce Affector31
        {
            force_aff_application               average
        }
        affector                                Scale Affector84
        {
            xyz_scale                           60
        }
    }
}
