system PU/attack_light_red
{
    scale 										0.06 0.06 0.06
    technique Technique3
    {
        visual_particle_quota                   6
        material                                PU/attack_light_red
        renderer                                Billboard
        {
        }
        emitter                                 Point Emitter4
        {
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
        }
        affector                                Colour Affector8
        {
            colour_aff_time_colour              0    0.8 0.2 0.2 1
            colour_aff_time_colour              2    1 0 0 1
        }
    }
}
