system PU/attack_light_red
{
    scale_velocity                              0.25
    scale                                       0.25 0.25 0.25
    technique 
    {
        visual_particle_quota                   15
        material                                PU/attack_light_red
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       dyn_oscillate
            {
                oscillate_frequency             0.8
                oscillate_phase                 180
                oscillate_base                  500
                oscillate_amplitude             500
                oscillate_type                  sine
            }
            time_to_live                        0.18
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             16
            }
            direction                           0 0 0
            colour                              0.75 0.25 0.25 1
            box_em_width                        24
            box_em_height                       6
            box_em_depth                        24
        }
    }
}
