system PU/any_jump_d
{
    scale                                       0.08 0.08 0.08
    technique Technique43
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   10
        material                                PU/any_jump_d
        spatial_hashtable_size                  2
        renderer                                Billboard
        {
            render_queue_group                  100
            common_direction                    1 1 1
        }
        emitter                                 Circle Emitter3
        {
            emission_rate                       dyn_random
            {
                min                             10
                max                             15
            }
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.6
            }
            mass                                2
            velocity                            20
            duration                            dyn_random
            {
                min                             0.4
                max                             0.6
            }
            circle_em_radius                    150
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
