system PU/bag_hearts_fountain_double
{
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique 
    {
        visual_particle_quota                   60
        material                                PU/bag_hearts_fountain_double
        default_particle_width                  36
        default_particle_height                 36
        default_particle_depth                  36
        renderer                                Billboard
        {
        }
        emitter                                 Circle myPointEmitter
        {
            angle                               30
            time_to_live                        2
            velocity                            350
            duration                            1
            colour                              0.85 0.15 0.15 1
            circle_em_radius                    50
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -400 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
