system PU/box_dust
{
    keep_local                                  true
    scale_velocity                              0.15
    scale                                       0.15 0.15 0.15
    technique Technique4
    {
        material                                PU/box_dust
        default_particle_width                  42
        default_particle_height                 42
        default_particle_depth                  42
        renderer                                Billboard
        {
        }
        emitter                                 Point Emitter5
        {
            emission_rate                       dyn_random
            {
                min                             6
                max                             8
            }
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             250
                max                             350
            }
            duration                            dyn_random
            {
                min                             0.6
                max                             0.8
            }
            keep_local                          true
        }
        affector                                LinearForce Affector39
        {
            force_aff_vector                    0 -400 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
    technique Technique4
    {
        material                                PU/box_dust_2
        default_particle_width                  42
        default_particle_height                 42
        default_particle_depth                  42
        renderer                                Billboard
        {
        }
        emitter                                 Point Emitter5
        {
            emission_rate                       dyn_random
            {
                min                             6
                max                             8
            }
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             250
                max                             350
            }
            duration                            dyn_random
            {
                min                             0.6
                max                             0.8
            }
            keep_local                          true
        }
        affector                                LinearForce Affector39
        {
            force_aff_vector                    0 -400 0
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
