system PU/changeworld_sky
{
    technique 
    {
        visual_particle_quota                   10000
        material                                PU/changeworld_sky
        default_particle_width                  20
        default_particle_height                 20
        default_particle_depth                  20
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       1000
            angle                               50
            time_to_live                        20
            velocity                            500
            duration                            5
            position                            0 1000 0
            direction                           0 -1 0
            box_em_width                        5000
            box_em_height                       10
            box_em_depth                        5000
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -100 0
        }
        affector                                Colour Affector_red
        {
            colour_aff_time_colour              0    0.9 0.1 0.1 1
        }
    }
    technique 
    {
        visual_particle_quota                   10000
        material                                PU/changeworld_sky
        default_particle_width                  20
        default_particle_height                 20
        default_particle_depth                  20
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       1000
            angle                               50
            time_to_live                        20
            velocity                            500
            duration                            5
            position                            0 1000 0
            direction                           0 -1 0
            box_em_width                        5000
            box_em_height                       10
            box_em_depth                        5000
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -100 0
        }
        affector                                Colour Affector_green
        {
            colour_aff_time_colour              0    0.1 0.9 0.1 1
        }
    }
    technique 
    {
        visual_particle_quota                   10000
        material                                PU/changeworld_sky
        default_particle_width                  20
        default_particle_height                 20
        default_particle_depth                  20
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       1000
            angle                               50
            time_to_live                        20
            velocity                            500
            duration                            5
            position                            0 1000 0
            direction                           0 -1 0
            box_em_width                        5000
            box_em_height                       10
            box_em_depth                        5000
        }
        affector                                LinearForce 
        {
            force_aff_vector                    0 -100 0
        }
        affector                                Colour Affector_blue
        {
            colour_aff_time_colour              0    0.1 0.1 0.9 1
        }
    }
}
