system PU/changeworld_changing
{
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique 
    {
        material                                PU/changeworld_changing
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        2
            velocity                            dyn_random
            {
                min                             400
                max                             600
            }
            particle_width                      dyn_random
            {
                min                             20
                max                             180
            }
            particle_height                     dyn_random
            {
                min                             500
                max                             1000
            }
            colour                              0.85 0.85 0.15 1
        }
        affector                                Colour 
        {
            colour_aff_time_colour              0    1 1 1 1
            colour_aff_time_colour              0.8  1 1 1 1
            colour_aff_time_colour              1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
