system PU/diamond_stars_cloud
{
    scale                                       0.065 0.065 0.065
    technique 
    {
        visual_particle_quota                   40
        material                                PU/diamond_stars_cloud
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       dyn_oscillate
            {
                oscillate_frequency             0.5
                oscillate_phase                 0
                oscillate_base                  200
                oscillate_amplitude             200
                oscillate_type                  sine
            }
            time_to_live                        0.2
            duration                            0.5
            all_particle_dimensions             dyn_random
            {
                min                             12
                max                             120
            }
            position                            0 20 0
            direction                           0 0 0
            colour                              0.25 0.5 0.75 1
            box_em_height                       150
        }
    }
}
