system PU/nest_break
{
    keep_local                                  true
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique Technique4
    {
        position                                0 175 0
        keep_local                              true
        material                                PU/nest_break
        default_particle_width                  24
        default_particle_height                 24
        default_particle_depth                  24
        renderer                                Billboard
        {
        }
        emitter                                 Box
        {
            emission_rate                       dyn_random
            {
                min                             12
                max                             15
            }
            angle                               30
            time_to_live                        dyn_random
            {
                min                             1.2
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             120
                max                             180
            }
            duration                            dyn_random
            {
                min                             0.8
                max                             1
            }
            keep_local                          true
            box_em_width                        80
            box_em_height                       10
            box_em_depth                        80
        }
        affector                                LinearForce Affector39
        {
            force_aff_vector                    0 -200 0
        }
        affector                                Colour Affector8
        {
            colour_aff_time_colour              0    0.9 0.8 0.9 1
        }
    }
}
