system PU/tripollo_shock
{
    technique Technique3
    {
        position                                0 200 0
        visual_particle_quota                   10
        material                                PU/tripollo_shock
        renderer                                Billboard
        {
        }
        emitter                                 Circle Emitter4
        {
            time_to_live                        0.8
            duration                            3
            direction                           0 0 0
            circle_em_radius                    150
            circle_em_step                      10
        }
    }
}
